"""corte diario

Revision ID: 2e2aaac64acf
Revises: 88b905bed3a6
Create Date: 2026-07-03 17:08:44.950289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2aaac64acf'
down_revision: Union[str, None] = '88b905bed3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total_ventas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_gastos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ganancia_neta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_pedidos', sa.Integer(), nullable=False),
    sa.Column('num_tickets', sa.Integer(), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('corte_metodos_pago',
    sa.Column('id_corte', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_corte'], ['cortes_diarios.id'], ),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id_corte', 'id_metodo_pago')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corte_metodos_pago')
    op.drop_table('cortes_diarios')
    # ### end Alembic commands ###
