services:
  coffee_code_db:
    image: postgres:15
    container_name: coffee_code_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_pass
      POSTGRES_DB: coffee_code
    ports:
      - "5434:5432"
    volumes:
      - coffee_code_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee_user -d coffee_code"]
      interval: 5s
      timeout: 5s
      retries: 10

  coffee_code_api:
    build: ./api
    container_name: coffee_code_api
    restart: unless-stopped
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://coffee_user:coffee_pass@coffee_code_db:5432/coffee_code
    ports:
      - "8010:8000"
    depends_on:
      coffee_code_db:
        condition: service_healthy
    volumes:
      - ./api:/app

volumes:
  coffee_code_db_data:
